  name: BrowserStack Web Tests

  on:
   workflow_dispatch:
     inputs:
       message:
         description: 'Message for manually triggering'
         required: false
         default: 'Triggered for Updates'
         type: string
   push:
     branches:
       - '!release-branch'
       - release*
       - master
       - 1.*
       - develop
    
  jobs:
    inji-web-test:
      runs-on: ubuntu-latest
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli                 
    
      - name: Run tests
        run: |
           cd inji-web-test
           mvn clean test -DtestngXmlFile="TestNg.xml"

      - name: Save test reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-reports
          path: inji-web-test/test-output
          
      - name: Upload to S3
        if: success() || failure()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1" 
          S3_BUCKET: "inji-stack"
          S3_OBJECT_KEY: "$REPO_NAME"
        run: |
          echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)"
          aws s3 cp inji-web-test/test-output s3://$S3_BUCKET/$S3_OBJECT_KEY/ --recursive                      
