  name: BrowserStack Web Tests

  on:
   workflow_dispatch:
     inputs:
       message:
         description: 'Message for manually triggering'
         required: false
         default: 'Triggered for Updates'
         type: string
   push:
     branches:
       - '!release-branch'
       - release*
       - master
       - 1.*
       - develop
    
  jobs:
    inji-web-test:
      uses: mohanraj209/kattu/.github/workflows/browserstack-web.yml@master-java21
      with:
        SERVICE_LOCATION: inji-web-test
        BUILD_ARTIFACT: test-output
      secrets:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}         
